import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

// Release signing: ada android/key.properties (CI) → upload keystore.
// Tanpa file itu (local) → fallback debug signing.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.iamutaki.sambasku"
    // permission_handler_android butuh compileSdk 37+
    compileSdk = 37
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.iamutaki.sambasku"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        // Default supaya IDE resolve ${deepLinkHost}; di-override per flavor
        // di flavorizr.gradle.kts.
        manifestPlaceholders["deepLinkHost"] = "sambasku-web-staging.iamutaki.com"
        manifestPlaceholders["appAuthRedirectScheme"] = "com.iamutaki.sambasku.staging"
    }

    if (keystorePropertiesFile.exists()) {
        signingConfigs {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
            }
        }
    }

    buildTypes {
        // Upload JKS di debug supaya SHA-1 Google Sign-In sama dengan APK
        // sideload/CI. Play Store menandatangani ulang dengan App signing
        // key; SHA itu didaftarkan terpisah di project GCP Web client.
        debug {
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
        release {
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    // AGP 8.x: lintVitalRelease sering gagal di CI; lint via flutter analyze.
    lint {
        checkReleaseBuilds = false
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}

dependencies {
    implementation("androidx.media3:media3-transformer:1.5.1")
    implementation("androidx.media3:media3-effect:1.5.1")
    implementation("com.google.guava:guava:33.3.1-android")
}

// Firebase Measurement menarik play-services-ads-identifier; library itu
// mendeklarasikan AD_ID. App tidak mengumpulkan advertising ID, jadi
// keluarkan modulnya dari classpath release/debug.
configurations.configureEach {
    exclude(group = "com.google.android.gms", module = "play-services-ads-identifier")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
